---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
builddrafts: false
taxonomies:
    tag: "tags"
    category: "categories"
    series: "series"
baseurl: http://bpesquet.fr
canonifyurls: true
disqusShortname: "bpesquet"
---
