---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
builddrafts: false
indexes:
   category: "categories"
   tag: "tags"
baseurl: http://test.bpesquet.fr
canonifyurls: true
disqusShortname: "baptistepesquet"
---
